apiVersion: v1
entries:
  camel-openshift-console-plugin:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2025-08-20T14:05:12.915741969+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: d5de87552c8da2d0074193709bde85a0266278bd14c3b054df65d4a01f910da0
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-openshift-console-plugin
    sources:
    - https://github.com/camel-tooling/camel-openshift-console-plugin.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard-charts/camel-openshift-console-plugin-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    created: "2025-07-29T11:20:02.974308211+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: d0188e1a59846597f0271d55122a57a5aaf882901cd466dc5bef1d8387c4ec0b
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-openshift-console-plugin
    sources:
    - https://github.com/camel-tooling/camel-openshift-console-plugin.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard-charts/camel-openshift-console-plugin-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-20T14:05:12.915337591+02:00"
