apiVersion: v1
entries:
  camel-dashboard-console:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2025-09-16T16:11:52.41654937+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 7770ec8b148a85beb077e45a8971777d4e2f8133a31406837363347dfee90984
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2025-09-16T15:52:09.385080176+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: a069929b68e6ab57bd045d1c2947b57d2368e7ebb9ca52adbafb934709ad0a0c
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.2.0.tgz
    version: 0.2.0
generated: "2025-09-16T16:11:52.416153207+02:00"
