apiVersion: v1
entries:
  camel-dashboard-console:
  - annotations:
      charts.openshift.io/name: Camel Dashboard OpenShift Console plugin
    apiVersion: v2
    appVersion: 0.5.1
    created: "2026-06-02T16:39:31.998963512+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: e42a12afd823bcbfe4ae04db6b365d30f19ac357dbdc30ce5b6cd48fc14b5c20
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - camel
    - dashboard
    - console
    - react
    kubeVersion: '>= 1.34'
    maintainers:
    - email: gfournier@apache.org
      name: gansheer
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.5.1.tgz
    version: 0.5.1
generated: "2026-06-02T16:39:31.998259432+02:00"
