apiVersion: v1
entries:
  camel-dashboard-console:
  - annotations:
      charts.openshift.io/name: Camel Dashboard OpenShift Console plugin
    apiVersion: v2
    appVersion: 0.5.0
    created: "2026-06-02T11:09:10.844986599+02:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: aa8121b97d58299704abb246e71b5fc21d3a2e6241b668785748b703780b71da
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - camel
    - dashboard
    - console
    - react
    kubeVersion: '>= 1.34'
    maintainers:
    - email: gfournier@apache.org
      name: gansheer
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.5.0.tgz
    version: 0.5.0
generated: "2026-06-02T11:09:10.844565099+02:00"
