---
plugin:
  name: ""
  description: ""
  image: ""
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  certificateSecretName: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  patcherServiceAccount:
    create: true
    annotations: {}
    name: ""
  jobs:
    patchConsoles:
      enabled: true
      image: "registry.redhat.io/openshift4/ose-tools-rhel8@sha256:e44074f21e0cca6464e50cb6ff934747e0bd11162ea01d522433a1a1ae116103"
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi

# Configure one or more view permissions to camelapps.camel.apache.org Custom Resources (GET LIST WATCH).
# The plugin needs the user to have access to the Custom Resources to be able to display them.
# This will create a Role and a RoleBinding for each namespace.
# The namespace and at least one subject a required to create a role/rolebinding pair.
camelAppRbac:
#  - namespace: my-project
#    subjects:
#      - apiGroup: rbac.authorization.k8s.io
#        kind: User
#        name: developer
#  - namespace: my-other-project
#    subjects:
#      - apiGroup: rbac.authorization.k8s.io
#        kind: Group
#        name: system:authenticated
#      - kind: ServiceAccount
#        name: camel-developer
#        namespace: openshift-monitoring

