name: Build

env:
  REGISTRY: "ghcr.io"
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Build plugin
        run: make plugin-build

      - name: Lint plugin
        continue-on-error: true
        run: make plugin-lint
        
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build plugin container
        shell: bash
        run: |
          make CUSTOM_PLUGIN_IMAGE=${{ env.REGISTRY }}/camel-tooling/camel-openshift-console-plugin plugin-image

      - name: Push plugin container
        shell: bash
        run: |
          make CUSTOM_PLUGIN_IMAGE=${{ env.REGISTRY }}/camel-tooling/camel-openshift-console-plugin plugin-image
          make CUSTOM_PLUGIN_IMAGE=${{ env.REGISTRY }}/camel-tooling/camel-openshift-console-plugin push-plugin
        

