name: Operator

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if:  github.ref == 'refs/heads/main'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - id: checkout-operator-repo
        name: Checkout Camel Dashboard Operator repo
        uses: actions/checkout@v4
        with:
          repository: camel-tooling/camel-dashboard-operator
          path: camel-dashboard-operator

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "camel-dashboard-operator/go.mod"
          check-latest: true

      - name: Build operator
        shell: bash
        run: |
          pushd camel-dashboard-operator
          NOTEST=1 make build
          NOTEST=1 CUSTOM_IMAGE=quay.io/camel-tooling/camel-dashboard-operator CUSTOM_VERSION=latest make images-all
          NOTEST=1 CUSTOM_IMAGE=quay.io/camel-tooling/camel-dashboard-operator CUSTOM_VERSION=latest make images-push-all
